package aggiuntanuovoprodotto;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.JavascriptExecutor;

public class AggiuntaProdottoTest {
	
	private WebDriver driver;
	  JavascriptExecutor js;
	  @Before
	  public void setUp() {
		  System.setProperty("webdriver.chrome.driver", "test/aggiuntanuovoprodotto/chromedriver.exe");
	    driver = new ChromeDriver();
	    js = (JavascriptExecutor) driver;
	  }
	  @After
	  public void tearDown() {
	    driver.quit();
	  }
	  
	  @Test
	  public void testAggiuntaProdotto() throws InterruptedException{ 
		    driver.get("http://localhost:8080/eSoccerce/site/index.jsp");
		    Thread.sleep(500);
		    driver.findElement(By.linkText("Login")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("email")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("email")).sendKeys("admin@admin.it");
		    Thread.sleep(500);
		    driver.findElement(By.id("password")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("password")).sendKeys("admin");
		    Thread.sleep(500);
		    driver.findElement(By.id("submit")).click();
		    Thread.sleep(500);
		    driver.findElement(By.linkText("Home")).click();
		    Thread.sleep(500);
		    driver.findElement(By.cssSelector("li:nth-child(1) > .dropdown > .text")).click();
		    Thread.sleep(500);
		    driver.findElement(By.linkText("Aggiungi prodotto")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("code")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("code")).sendKeys("123");
		    Thread.sleep(500);
		    driver.findElement(By.id("urlimage")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("urlimage")).sendKeys("/src/immagine.png");
		    Thread.sleep(500);
		    driver.findElement(By.id("nomeprodotto")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("nomeprodotto")).sendKeys("Maglietta Milan");
		    Thread.sleep(500);
		    driver.findElement(By.id("marca")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("marca")).sendKeys("Puma");
		    Thread.sleep(500);
		    driver.findElement(By.id("descrizione")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("descrizione")).sendKeys("Maglietta Milan Authentic 2023");
		    Thread.sleep(500);
		    driver.findElement(By.id("prezzo")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("prezzo")).sendKeys("59");
		    Thread.sleep(500);
		    driver.findElement(By.id("quantità")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("quantità")).sendKeys("5");
		    Thread.sleep(500);
		    driver.findElement(By.id("taglia")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("taglia")).sendKeys("XL");
		    Thread.sleep(500);
		    driver.findElement(By.id("submit")).click();
		    assertThat(driver.getTitle(), is("eSoccerce - Prodotto aggiunto!"));
		    Thread.sleep(3000);
		  }

	@Test
	  public void testCodiceProdottoNonInserito() throws InterruptedException {
		    driver.get("http://localhost:8080/eSoccerce/site/index.jsp");
		    Thread.sleep(500);
		    driver.findElement(By.linkText("Login")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("email")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("email")).sendKeys("admin@admin.it");
		    Thread.sleep(500);
		    driver.findElement(By.id("password")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("password")).sendKeys("admin");
		    Thread.sleep(500);
		    driver.findElement(By.id("submit")).click();
		    Thread.sleep(500);
		    driver.findElement(By.linkText("Home")).click();
		    Thread.sleep(500);
		    driver.findElement(By.cssSelector("li:nth-child(1) > .dropdown > .text")).click();
		    Thread.sleep(500);
		    driver.findElement(By.linkText("Aggiungi prodotto")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("urlimage")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("urlimage")).sendKeys("/src/immagine.png");
		    Thread.sleep(500);
		    driver.findElement(By.id("nomeprodotto")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("nomeprodotto")).sendKeys("Maglietta Milan");
		    Thread.sleep(500);
		    driver.findElement(By.id("marca")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("marca")).sendKeys("Puma");
		    Thread.sleep(500);
		    driver.findElement(By.id("descrizione")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("descrizione")).sendKeys("Maglietta Milan Authentic 2023");
		    Thread.sleep(500);
		    driver.findElement(By.id("prezzo")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("prezzo")).sendKeys("59");
		    Thread.sleep(500);
		    driver.findElement(By.id("quantità")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("quantità")).sendKeys("5");
		    Thread.sleep(500);
		    driver.findElement(By.id("taglia")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("taglia")).sendKeys("XL");
		    Thread.sleep(500);
		    driver.findElement(By.id("submit")).click();
		    assertThat(driver.getTitle(), is("eSoccerce - Aggiungi prodotto"));
		    Thread.sleep(3000);
		  }
	  
	  @Test
	  public void testPathImmagineNonInserito() throws InterruptedException{
		  driver.get("http://localhost:8080/eSoccerce/site/index.jsp");
		    Thread.sleep(500);
		    driver.findElement(By.linkText("Login")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("email")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("email")).sendKeys("admin@admin.it");
		    Thread.sleep(500);
		    driver.findElement(By.id("password")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("password")).sendKeys("admin");
		    Thread.sleep(500);
		    driver.findElement(By.id("submit")).click();
		    Thread.sleep(500);
		    driver.findElement(By.linkText("Home")).click();
		    Thread.sleep(500);
		    driver.findElement(By.cssSelector("li:nth-child(1) > .dropdown > .text")).click();
		    Thread.sleep(500);
		    driver.findElement(By.linkText("Aggiungi prodotto")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("code")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("code")).sendKeys("123");
		    Thread.sleep(500);
		    driver.findElement(By.id("nomeprodotto")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("nomeprodotto")).sendKeys("Maglietta Milan");
		    Thread.sleep(500);
		    driver.findElement(By.id("marca")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("marca")).sendKeys("Puma");
		    Thread.sleep(500);
		    driver.findElement(By.id("descrizione")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("descrizione")).sendKeys("Maglietta Milan Authentic 2023");
		    Thread.sleep(500);
		    driver.findElement(By.id("prezzo")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("prezzo")).sendKeys("59");
		    Thread.sleep(500);
		    driver.findElement(By.id("quantità")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("quantità")).sendKeys("5");
		    Thread.sleep(500);
		    driver.findElement(By.id("taglia")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("taglia")).sendKeys("XL");
		    Thread.sleep(500);
		    driver.findElement(By.id("submit")).click();
		    assertThat(driver.getTitle(), is("eSoccerce - Aggiungi prodotto"));
		    Thread.sleep(3000);
		  
	  }
	  
	  @Test
	  public void testNomeNonInserito() throws InterruptedException{
		  driver.get("http://localhost:8080/eSoccerce/site/index.jsp");
		    Thread.sleep(500);
		    driver.findElement(By.linkText("Login")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("email")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("email")).sendKeys("admin@admin.it");
		    Thread.sleep(500);
		    driver.findElement(By.id("password")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("password")).sendKeys("admin");
		    Thread.sleep(500);
		    driver.findElement(By.id("submit")).click();
		    Thread.sleep(500);
		    driver.findElement(By.linkText("Home")).click();
		    Thread.sleep(500);
		    driver.findElement(By.cssSelector("li:nth-child(1) > .dropdown > .text")).click();
		    Thread.sleep(500);
		    driver.findElement(By.linkText("Aggiungi prodotto")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("code")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("code")).sendKeys("123");
		    Thread.sleep(500);
		    driver.findElement(By.id("urlimage")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("urlimage")).sendKeys("/src/immagine.png");
		    Thread.sleep(500);
		    driver.findElement(By.id("marca")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("marca")).sendKeys("Puma");
		    Thread.sleep(500);
		    driver.findElement(By.id("descrizione")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("descrizione")).sendKeys("Maglietta Milan Authentic 2023");
		    Thread.sleep(500);
		    driver.findElement(By.id("prezzo")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("prezzo")).sendKeys("59");
		    Thread.sleep(500);
		    driver.findElement(By.id("quantità")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("quantità")).sendKeys("5");
		    Thread.sleep(500);
		    driver.findElement(By.id("taglia")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("taglia")).sendKeys("XL");
		    Thread.sleep(500);
		    driver.findElement(By.id("submit")).click();
		    assertThat(driver.getTitle(), is("eSoccerce - Aggiungi prodotto"));
		    Thread.sleep(3000);
	  }
	  
	  @Test
	  public void testMarcaNonInserita() throws InterruptedException{
		  driver.get("http://localhost:8080/eSoccerce/site/index.jsp");
		    Thread.sleep(500);
		    driver.findElement(By.linkText("Login")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("email")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("email")).sendKeys("admin@admin.it");
		    Thread.sleep(500);
		    driver.findElement(By.id("password")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("password")).sendKeys("admin");
		    Thread.sleep(500);
		    driver.findElement(By.id("submit")).click();
		    Thread.sleep(500);
		    driver.findElement(By.linkText("Home")).click();
		    Thread.sleep(500);
		    driver.findElement(By.cssSelector("li:nth-child(1) > .dropdown > .text")).click();
		    Thread.sleep(500);
		    driver.findElement(By.linkText("Aggiungi prodotto")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("code")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("code")).sendKeys("123");
		    Thread.sleep(500);
		    driver.findElement(By.id("urlimage")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("urlimage")).sendKeys("/src/immagine.png");
		    Thread.sleep(500);
		    driver.findElement(By.id("nomeprodotto")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("nomeprodotto")).sendKeys("Maglietta Milan");
		    Thread.sleep(500);
		    driver.findElement(By.id("descrizione")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("descrizione")).sendKeys("Maglietta Milan Authentic 2023");
		    Thread.sleep(500);
		    driver.findElement(By.id("prezzo")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("prezzo")).sendKeys("59");
		    Thread.sleep(500);
		    driver.findElement(By.id("quantità")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("quantità")).sendKeys("5");
		    Thread.sleep(500);
		    driver.findElement(By.id("taglia")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("taglia")).sendKeys("XL");
		    Thread.sleep(500);
		    driver.findElement(By.id("submit")).click();
		    assertThat(driver.getTitle(), is("eSoccerce - Aggiungi prodotto"));
		    Thread.sleep(3000);
	  }
	  
	  @Test
	  public void testDescrizioneNonInserita() throws InterruptedException{
		  driver.get("http://localhost:8080/eSoccerce/site/index.jsp");
		    Thread.sleep(500);
		    driver.findElement(By.linkText("Login")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("email")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("email")).sendKeys("admin@admin.it");
		    Thread.sleep(500);
		    driver.findElement(By.id("password")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("password")).sendKeys("admin");
		    Thread.sleep(500);
		    driver.findElement(By.id("submit")).click();
		    Thread.sleep(500);
		    driver.findElement(By.linkText("Home")).click();
		    Thread.sleep(500);
		    driver.findElement(By.cssSelector("li:nth-child(1) > .dropdown > .text")).click();
		    Thread.sleep(500);
		    driver.findElement(By.linkText("Aggiungi prodotto")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("code")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("code")).sendKeys("123");
		    Thread.sleep(500);
		    driver.findElement(By.id("urlimage")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("urlimage")).sendKeys("/src/immagine.png");
		    Thread.sleep(500);
		    driver.findElement(By.id("nomeprodotto")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("nomeprodotto")).sendKeys("Maglietta Milan");
		    Thread.sleep(500);
		    driver.findElement(By.id("marca")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("marca")).sendKeys("Puma");
		    Thread.sleep(500);
		    driver.findElement(By.id("prezzo")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("prezzo")).sendKeys("59");
		    Thread.sleep(500);
		    driver.findElement(By.id("quantità")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("quantità")).sendKeys("5");
		    Thread.sleep(500);
		    driver.findElement(By.id("taglia")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("taglia")).sendKeys("XL");
		    Thread.sleep(500);
		    driver.findElement(By.id("submit")).click();
		    assertThat(driver.getTitle(), is("eSoccerce - Aggiungi prodotto"));
		    Thread.sleep(3000);
	  }
	  
	  @Test
	  public void testPrezzoNonInserito() throws InterruptedException {
		  driver.get("http://localhost:8080/eSoccerce/site/index.jsp");
		    Thread.sleep(500);
		    driver.findElement(By.linkText("Login")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("email")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("email")).sendKeys("admin@admin.it");
		    Thread.sleep(500);
		    driver.findElement(By.id("password")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("password")).sendKeys("admin");
		    Thread.sleep(500);
		    driver.findElement(By.id("submit")).click();
		    Thread.sleep(500);
		    driver.findElement(By.linkText("Home")).click();
		    Thread.sleep(500);
		    driver.findElement(By.cssSelector("li:nth-child(1) > .dropdown > .text")).click();
		    Thread.sleep(500);
		    driver.findElement(By.linkText("Aggiungi prodotto")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("code")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("code")).sendKeys("123");
		    Thread.sleep(500);
		    driver.findElement(By.id("urlimage")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("urlimage")).sendKeys("/src/immagine.png");
		    Thread.sleep(500);
		    driver.findElement(By.id("nomeprodotto")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("nomeprodotto")).sendKeys("Maglietta Milan");
		    Thread.sleep(500);
		    driver.findElement(By.id("marca")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("marca")).sendKeys("Puma");
		    Thread.sleep(500);
		    driver.findElement(By.id("descrizione")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("descrizione")).sendKeys("Maglietta Milan Authentic 2023");
		    Thread.sleep(500);
		    driver.findElement(By.id("quantità")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("quantità")).sendKeys("5");
		    Thread.sleep(500);
		    driver.findElement(By.id("taglia")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("taglia")).sendKeys("XL");
		    Thread.sleep(500);
		    driver.findElement(By.id("submit")).click();
		    assertThat(driver.getTitle(), is("eSoccerce - Aggiungi prodotto"));
		    Thread.sleep(3000);
	  }
	  
	  @Test
	  public void testQuantitàNonInserita() throws InterruptedException{
		  driver.get("http://localhost:8080/eSoccerce/site/index.jsp");
		    Thread.sleep(500);
		    driver.findElement(By.linkText("Login")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("email")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("email")).sendKeys("admin@admin.it");
		    Thread.sleep(500);
		    driver.findElement(By.id("password")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("password")).sendKeys("admin");
		    Thread.sleep(500);
		    driver.findElement(By.id("submit")).click();
		    Thread.sleep(500);
		    driver.findElement(By.linkText("Home")).click();
		    Thread.sleep(500);
		    driver.findElement(By.cssSelector("li:nth-child(1) > .dropdown > .text")).click();
		    Thread.sleep(500);
		    driver.findElement(By.linkText("Aggiungi prodotto")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("code")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("code")).sendKeys("123");
		    Thread.sleep(500);
		    driver.findElement(By.id("urlimage")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("urlimage")).sendKeys("/src/immagine.png");
		    Thread.sleep(500);
		    driver.findElement(By.id("nomeprodotto")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("nomeprodotto")).sendKeys("Maglietta Milan");
		    Thread.sleep(500);
		    driver.findElement(By.id("marca")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("marca")).sendKeys("Puma");
		    Thread.sleep(500);
		    driver.findElement(By.id("descrizione")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("descrizione")).sendKeys("Maglietta Milan Authentic 2023");
		    Thread.sleep(500);
		    driver.findElement(By.id("prezzo")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("prezzo")).sendKeys("59");
		    Thread.sleep(500);
		    driver.findElement(By.id("taglia")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("taglia")).sendKeys("XL");
		    Thread.sleep(500);
		    driver.findElement(By.id("submit")).click();
		    assertThat(driver.getTitle(), is("eSoccerce - Aggiungi prodotto"));
		    Thread.sleep(3000);
	  }
	  
	  @Test
	  public void testTagliaNonValida() throws InterruptedException{
		  driver.get("http://localhost:8080/eSoccerce/site/index.jsp");
		    Thread.sleep(500);
		    driver.findElement(By.linkText("Login")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("email")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("email")).sendKeys("admin@admin.it");
		    Thread.sleep(500);
		    driver.findElement(By.id("password")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("password")).sendKeys("admin");
		    Thread.sleep(500);
		    driver.findElement(By.id("submit")).click();
		    Thread.sleep(500);
		    driver.findElement(By.linkText("Home")).click();
		    Thread.sleep(500);
		    driver.findElement(By.cssSelector("li:nth-child(1) > .dropdown > .text")).click();
		    Thread.sleep(500);
		    driver.findElement(By.linkText("Aggiungi prodotto")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("code")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("code")).sendKeys("123");
		    Thread.sleep(500);
		    driver.findElement(By.id("urlimage")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("urlimage")).sendKeys("/src/immagine.png");
		    Thread.sleep(500);
		    driver.findElement(By.id("nomeprodotto")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("nomeprodotto")).sendKeys("Maglietta Milan");
		    Thread.sleep(500);
		    driver.findElement(By.id("marca")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("marca")).sendKeys("Puma");
		    Thread.sleep(500);
		    driver.findElement(By.id("descrizione")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("descrizione")).sendKeys("Maglietta Milan Authentic 2023");
		    Thread.sleep(500);
		    driver.findElement(By.id("prezzo")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("prezzo")).sendKeys("59");
		    Thread.sleep(500);
		    driver.findElement(By.id("quantità")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("quantità")).sendKeys("5");
		    Thread.sleep(500);
		    driver.findElement(By.id("taglia")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("taglia")).sendKeys("XL!");
		    Thread.sleep(500);
		    driver.findElement(By.id("submit")).click();
		    assertThat(driver.getTitle(), is("eSoccerce - Aggiungi prodotto"));
		    Thread.sleep(3000);
	  }
	  
	  @Test
	  public void testNumeroNonValido() throws InterruptedException {
		  driver.get("http://localhost:8080/eSoccerce/site/index.jsp");
		    Thread.sleep(500);
		    driver.findElement(By.linkText("Login")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("email")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("email")).sendKeys("admin@admin.it");
		    Thread.sleep(500);
		    driver.findElement(By.id("password")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("password")).sendKeys("admin");
		    Thread.sleep(500);
		    driver.findElement(By.id("submit")).click();
		    Thread.sleep(500);
		    driver.findElement(By.linkText("Home")).click();
		    Thread.sleep(500);
		    driver.findElement(By.cssSelector("li:nth-child(1) > .dropdown > .text")).click();
		    Thread.sleep(500);
		    driver.findElement(By.linkText("Aggiungi prodotto")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("code")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("code")).sendKeys("123");
		    Thread.sleep(500);
		    driver.findElement(By.id("urlimage")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("urlimage")).sendKeys("/src/immagine.png");
		    Thread.sleep(500);
		    driver.findElement(By.id("nomeprodotto")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("nomeprodotto")).sendKeys("Maglietta Milan");
		    Thread.sleep(500);
		    driver.findElement(By.id("marca")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("marca")).sendKeys("Puma");
		    Thread.sleep(500);
		    driver.findElement(By.id("descrizione")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("descrizione")).sendKeys("Maglietta Milan Authentic 2023");
		    Thread.sleep(500);
		    driver.findElement(By.id("prezzo")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("prezzo")).sendKeys("59");
		    Thread.sleep(500);
		    driver.findElement(By.id("quantità")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("quantità")).sendKeys("5");
		    Thread.sleep(500);
		    driver.findElement(By.id("numero")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("numero")).sendKeys("!");
		    Thread.sleep(500);
		    driver.findElement(By.id("submit")).click();
		    assertThat(driver.getTitle(), is("eSoccerce - Aggiungi prodotto"));
		    Thread.sleep(3000);
	  }
	  
	  @Test
	  public void testDimensioneNonValida() throws InterruptedException{
		  driver.get("http://localhost:8080/eSoccerce/site/index.jsp");
		    Thread.sleep(500);
		    driver.findElement(By.linkText("Login")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("email")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("email")).sendKeys("admin@admin.it");
		    Thread.sleep(500);
		    driver.findElement(By.id("password")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("password")).sendKeys("admin");
		    Thread.sleep(500);
		    driver.findElement(By.id("submit")).click();
		    Thread.sleep(500);
		    driver.findElement(By.linkText("Home")).click();
		    Thread.sleep(500);
		    driver.findElement(By.cssSelector("li:nth-child(1) > .dropdown > .text")).click();
		    Thread.sleep(500);
		    driver.findElement(By.linkText("Aggiungi prodotto")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("code")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("code")).sendKeys("123");
		    Thread.sleep(500);
		    driver.findElement(By.id("urlimage")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("urlimage")).sendKeys("/src/immagine.png");
		    Thread.sleep(500);
		    driver.findElement(By.id("nomeprodotto")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("nomeprodotto")).sendKeys("Maglietta Milan");
		    Thread.sleep(500);
		    driver.findElement(By.id("marca")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("marca")).sendKeys("Puma");
		    Thread.sleep(500);
		    driver.findElement(By.id("descrizione")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("descrizione")).sendKeys("Maglietta Milan Authentic 2023");
		    Thread.sleep(500);
		    driver.findElement(By.id("prezzo")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("prezzo")).sendKeys("59");
		    Thread.sleep(500);
		    driver.findElement(By.id("quantità")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("quantità")).sendKeys("5");
		    Thread.sleep(500);
		    driver.findElement(By.id("dimensione")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("dimensione")).sendKeys("!");
		    Thread.sleep(500);
		    driver.findElement(By.id("submit")).click();
		    assertThat(driver.getTitle(), is("eSoccerce - Aggiungi prodotto"));
		    Thread.sleep(3000);
	  }
	  
	  @Test
	  public void testTipoNonValido() throws InterruptedException {
		  driver.get("http://localhost:8080/eSoccerce/site/index.jsp");
		    Thread.sleep(500);
		    driver.findElement(By.linkText("Login")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("email")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("email")).sendKeys("admin@admin.it");
		    Thread.sleep(500);
		    driver.findElement(By.id("password")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("password")).sendKeys("admin");
		    Thread.sleep(500);
		    driver.findElement(By.id("submit")).click();
		    Thread.sleep(500);
		    driver.findElement(By.linkText("Home")).click();
		    Thread.sleep(500);
		    driver.findElement(By.cssSelector("li:nth-child(1) > .dropdown > .text")).click();
		    Thread.sleep(500);
		    driver.findElement(By.linkText("Aggiungi prodotto")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("code")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("code")).sendKeys("123");
		    Thread.sleep(500);
		    driver.findElement(By.id("urlimage")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("urlimage")).sendKeys("/src/immagine.png");
		    Thread.sleep(500);
		    driver.findElement(By.id("nomeprodotto")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("nomeprodotto")).sendKeys("Maglietta Milan");
		    Thread.sleep(500);
		    driver.findElement(By.id("marca")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("marca")).sendKeys("Puma");
		    Thread.sleep(500);
		    driver.findElement(By.id("descrizione")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("descrizione")).sendKeys("Maglietta Milan Authentic 2023");
		    Thread.sleep(500);
		    driver.findElement(By.id("prezzo")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("prezzo")).sendKeys("59");
		    Thread.sleep(500);
		    driver.findElement(By.id("quantità")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("quantità")).sendKeys("5");
		    Thread.sleep(500);
		    driver.findElement(By.id("tipo")).click();
		    Thread.sleep(500);
		    driver.findElement(By.id("tipo")).sendKeys("!");
		    Thread.sleep(500);
		    driver.findElement(By.id("submit")).click();
		    assertThat(driver.getTitle(), is("eSoccerce - Aggiungi prodotto"));
		    Thread.sleep(3000);
	  }
	  
}


